<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Pagerfanta\Pagerfanta;
use Pagerfanta\Adapter\DoctrineORMAdapter;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function findAllPaginated($page)
    {

        $adapter = new DoctrineORMAdapter(
            $this->queryAll()
        );

        $pagerfanta = new Pagerfanta($adapter);
        $pagerfanta->setMaxPerPage(2); //TODO: move to entity class
        $pagerfanta ->setCurrentPage($page);

        return $pagerfanta;

    }

 protected function queryAll()
    {
        return $this -> _em -> createQueryBuilder()
            ->select( 't')
            ->from('AppBundle:Tag',  't');
    }



}
