<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Pagerfanta\Pagerfanta;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use AppBundle\Entity\Tag;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    /**
     * Gets all records paginated.
     *
     * @param int $page Page number
     *
     * @return \Pagerfanta\Pagerfanta Result
     */
    public function findAllPaginated($page)
    {

        $adapter = new DoctrineORMAdapter(
            $this->queryAll()
        );

        $pagerfanta = new Pagerfanta($adapter);
        $pagerfanta->setMaxPerPage(2); //TODO: move to entity class
        $pagerfanta ->setCurrentPage($page);

        return $pagerfanta;
    }

    protected function queryAll()
    {
        return $this -> _em -> createQueryBuilder()
            ->select('t')
            ->from('AppBundle:Tag', 't');
    }

    /**
     * Save entity.
     *
     * @param Tag $tag Tag entity
     */
    public function save(Tag $tag)
    {
        $this->_em->persist($tag);// cos jak aktywny rekord
        $this->_em->flush();
    }

    /**
     * Delete entity.
     *
     * @param Tag $tag Tag entity
     */
    public function delete(Tag $tag)
    {
        $this->_em->remove($tag);
        $this->_em->flush();
    }

}
